import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.CrystallographyChemistrySmallMoleculeCrystallographyCanonicalLaneLean.SpaceGroupClassification
import HautevilleHouse.CrystallographyChemistrySmallMoleculeCrystallographyCanonicalLaneLean.BravaisLattice
import HautevilleHouse.CrystallographyChemistrySmallMoleculeCrystallographyCanonicalLaneLean.XRayDiffraction
import HautevilleHouse.CrystallographyChemistrySmallMoleculeCrystallographyCanonicalLaneLean.Quasicrystal
import HautevilleHouse.CrystallographyChemistrySmallMoleculeCrystallographyCanonicalLaneLean.SmallMoleculeRefinement

namespace HautevilleHouse
namespace CrystallographyChemistrySmallMoleculeCrystallographyCanonicalLaneLean

def ConstrainedCrystallographyClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_crystallography_endgame (A : AdmissibleClass) :
    ConstrainedCrystallographyClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end CrystallographyChemistrySmallMoleculeCrystallographyCanonicalLaneLean
end HautevilleHouse